---
- name: Install noVNC dependancies
  sudo: yes
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
       cache_valid_time=3600
  with_items:
    - x11vnc
    - python
    - python-numpy
  tags: install

- name: Fetch noVNC
  git: repo=https://github.com/kanaka/noVNC.git
       version=v0.5.1
       dest=/noVNC
  tags: install

- name: Change permissions of noVNC to be owned by df user
  file: path=/noVNC
        recurse=yes
        owner=df
        group=df
  tags: install

- name: Set PRINT_MODE to 2D in df configuration
  lineinfile: dest=/df_linux/data/init/init.txt
              regexp='^\[PRINT_MODE\:(.*)$'
              line=[PRINT_MODE:2D]
              state=present
              backrefs=yes
  tags: configure

- name: Set WINDOWED to NO in df configuration
  lineinfile: dest=/df_linux/data/init/init.txt
              regexp='^\[WINDOWED\:(.*)$'
              line=[WINDOWED:NO]
              state=present
              backrefs=yes
  tags: configure

- include: supervisor.yml