---
- name: Restart supervisor
  become: yes
  service: name=supervisor state=restarted

- name: Reread supervisor
  become: yes
  command: supervisorctl reread

- name: Update supervisord
  become: yes
  command: supervisorctl update
