---
- name: Install gitwatch dependancies
  sudo: yes
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
       cache_valid_time=3600
  with_items:
    - git
    - inotify-tools
  tags: install

- name: Add gitwatch script
  get_url: url=https://raw.githubusercontent.com/nevik/gitwatch/master/gitwatch.sh
           dest=/gitwatch.sh
           mode=0755
  tags:
    - install

- name: Add gitwatch wrapper script
  sudo: yes
  template: src=setup-gitwatch.j2
            dest=/setup-gitwatch.sh
            mode=0755
  tags:
    - install

- name: Configure .gitconfig file
  template: src=gitconfig.j2
            dest=/home/df/.gitconfig
            owner=df
            group=df
  tags:
    - install
    - configure

- name: Set INITIAL_SAVE to YES in df configuration
  lineinfile: dest=/df_linux/data/init/init.txt
              regexp='^\[INITIAL_SAVE\:(.*)$'
              line=[INITIAL_SAVE:YES]
              state=present
              backrefs=yes
  tags: configure

- name: Set COMPRESSED_SAVES to NO in df configuration
  lineinfile: dest=/df_linux/data/init/init.txt
              regexp='^\[COMPRESSED_SAVES\:(.*)$'
              line=[COMPRESSED_SAVES:NO]
              state=present
              backrefs=yes
  tags: configure

- include: supervisor.yml