---
- name: enable multiarch
  command: dpkg --add-architecture i386

- name: Install df dependancies
  sudo: yes
  apt: pkg={{ item }}
       state=latest
       update_cache=yes
       cache_valid_time=3600
  with_items:
    - curl
    - tar
    - bzip2
    - git
    - libgtk2.0-0:i386
    - libglu1-mesa:i386
    - libsdl-image1.2:i386
    - libsdl-sound1.2:i386
    - libsdl-ttf2.0-0:i386
    - libopenal1:i386
    - unzip
  tags: install

- name: Ensure df group exist
  group: name=df gid=14503 state=present
  sudo: yes
  tags:
  - install

- name: Ensure df user exist
  user: name=df uid=14503 group=df state=present
  sudo: yes
  tags:
  - install